name: secure_messenger
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  barcode_scan2: ^4.2.4
  # crypto: ^3.0.3
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.1
  firebase_database: ^10.2.5
  firebase_storage: ^11.2.6
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.4
  image_picker: ^1.0.4
  local_auth: ^2.1.6
  provider: ^6.0.5
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.0
  webcrypto: ^0.5.3
  video_player: ^2.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
