// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1U4qCZqqG_g1f8hi3iGWHgd9np1Zm2G4',
    appId: '1:870762296160:android:3f5547487e8327518a6405',
    messagingSenderId: '870762296160',
    projectId: 'messenger-97df7',
    databaseURL: 'https://messenger-97df7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'messenger-97df7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsicCWnVqvTNaLsOKP0TSPf6fjRzzRY3Y',
    appId: '1:870762296160:ios:56ea972c2162ebc28a6405',
    messagingSenderId: '870762296160',
    projectId: 'messenger-97df7',
    databaseURL: 'https://messenger-97df7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'messenger-97df7.appspot.com',
    androidClientId: '870762296160-sp6utgr52l5mmpitbv8blnuu70v4efh9.apps.googleusercontent.com',
    iosClientId: '870762296160-7kudg18ttaj2jb4vj730931g1qt95mmp.apps.googleusercontent.com',
    iosBundleId: 'com.example.secureMessenger',
  );
}
